version: "3.9"

volumes:
  pg-data:

services:
  db:
    image: postgres:14.6
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./tools/postgres-initdb:/docker-entrypoint-initdb.d"
      - "pg-data:/var/lib/postgresql/data"