version: "3.9"

volumes:
  pg-data:

services:
  db:
    image: postgres:14.6
    environment:
      POSTGRES_DB: persistent_developer
      POSTGRES_PASSWORD: postgres
    volumes:
      - "../postgres-initdb:/docker-entrypoint-initdb.d"
      - "pg-data:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  developer-service:
    image: persistent-developer
    environment:
      PD_DB_HOST: db
    ports:
      - "10538:10538"
    depends_on:
      db:
        condition: service_healthy